name: CI & CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Schedule
        run: |
          python RunSchedule.py
          python WorkoutSchedule.py
          python VO2MaxSchedule.py

  deploy:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: Create Zip
        run: |
          zip -r WorkoutReminder.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:        ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:    ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:               ${{ secrets.AWS_REGION }}


      - name: Update Lambda Code
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://WorkoutReminder.zip